# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: bitconsulting
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: moneoapiv4
# "service" is the name of this project. This will also be added to your AWS resource names.
service: moneoapiv4

provider:
  name: aws
  runtime: python3.12
  region: us-east-2

functions:
  api:
    handler: lambda_function.handler
    layers:
      - arn:aws:lambda:us-east-2:869935111448:layer:ASGI_fastAPI:1
      - arn:aws:lambda:us-east-2:869935111448:layer:python-multipart:1
    events:
      - http:
          path: /{proxy+}
          method: ANY
